services:
  ecommerce-dashboard:

    environment:
      - TZ=America/Sao_Paulo

    container_name: ecommerce-dashboard

    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"

    volumes:
      - ../:/home/user/app
    
    command: sh -c "chmod +x .docker/start.sh && ./.docker/start.sh"
    
    extra_hosts:
      - "host.docker.internal:host-gateway" # C:\Windows\System32\drivers\etc\hosts -> 127.0.0.1    host.docker.internal
